Improve checks to increase code coverage.
git-svn-id: svn+ssh://svn.nta-monitor.com/trunk/opensource/ike-scan@9790 062a1500-4a13-0410-a63b-ee65f32af78f

diff --git a/check-packet b/check-packet
--- a/check-packet
+++ b/check-packet
@@ -10,15 +10,21 @@
 # It uses the undocumented ike-scan option --writepkttofile to write the
 # packet to a file rather than sending it via the network.
 #
+# It tries to use as many options as possible, in order to gain the maximum
+# code coverage.  For this reason, some of the option combinations may appear
+# strange.
+#
 TMPFILE=/tmp/ike-scan-test.$$.tmp
 #
 SAMPLE01="$srcdir/pkt-default-proposal.dat"
 SAMPLE02="$srcdir/pkt-custom-proposal.dat"
 SAMPLE03="$srcdir/pkt-aggressive.dat"
+SAMPLE04="$srcdir/pkt-malformed.dat"
+SAMPLE05="$srcdir/pkt-ikev2.dat"
 #
-echo "Checking default ike-scan packet against $SAMPLE01 ..."
-IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef"
-$srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE 127.0.0.1 >/dev/null 2>&1
+echo "Checking ike-scan default packet against $SAMPLE01 ..."
+IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --file=- --timeout=100 --interval=50 --quiet --timestamp --shownum --backoff=2.0"
+echo "127.0.0.1" | $srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE >/dev/null 2>&1
 if test $? -ne 0; then
    rm -f $TMPFILE
    echo "FAILED"
@@ -33,8 +39,8 @@ fi
 echo "ok"
 rm -f $TMPFILE
 #
-echo "Checking custom ike-scan packet against $SAMPLE02 ..."
-IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --mbz=255 --trans=(1=1,2=1,3=1,4=1) --vendor=deadbeef"
+echo "Checking ike-scan custom packet (adv trans) against $SAMPLE02 ..."
+IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --mbz=255 --trans=(1=1,2=1,3=1,4=1) --trans=(1=7/128,2=1,3=3,4=5) --vendor=deadbeef --vendor=00010203 --bandwidth=64K"
 $srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE 127.0.0.1 >/dev/null 2>&1
 if test $? -ne 0; then
    rm -f $TMPFILE
@@ -50,8 +56,8 @@ fi
 echo "ok"
 rm -f $TMPFILE
 #
-echo "Checking aggressive ike-scan packet against $SAMPLE03 ..."
-IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --randomseed=1234 --aggressive --id=royhills@hotmail.com"
+echo "Checking ike-scan aggressive mode packet against $SAMPLE03 ..."
+IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --randomseed=1234 --aggressive --id=royhills@hotmail.com --idtype=3 --dhgroup=2 --noncelen=20"
 $srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE 127.0.0.1 >/dev/null 2>&1
 if test $? -ne 0; then
    rm -f $TMPFILE
@@ -61,6 +67,40 @@ fi
 cmp -s $TMPFILE $SAMPLE03
 if test $? -ne 0; then
    rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f $TMPFILE
+#
+echo "Checking ike-scan malformed packet against $SAMPLE04 ..."
+IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --randomseed=1234 --multiline --lifetime=32 --lifesize=64 --auth=3 --gssid=deadbeef --headerlen=+10 --headerver=0x32  --certreq=203040 --doi=2 --situation=3 --protocol=4 --transid=5 --spisize=4 --hdrflags=127 --hdrmsgid=1234 --exchange=6 --nextpayload=57 --rcookie=deadbeefdeadbeef"
+$srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE 127.0.0.1 >/dev/null 2>&1
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+cmp -s $TMPFILE $SAMPLE04
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f $TMPFILE
+#
+echo "Checking ike-scan IKEv2 packet against $SAMPLE05 ..."
+IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --randomseed=1234 --ikev2"
+$srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE 127.0.0.1 >/dev/null 2>&1
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+cmp -s $TMPFILE $SAMPLE05
+if test $? -ne 0; then
+#   rm -f $TMPFILE
    echo "FAILED"
    exit 1
 fi
