Added aggressive mode packet test, made possible by repeatable PRNG. Improved random_ip() so it doesn't generate obviously invalid addresses. Incremented version number to 1.8.4.
git-svn-id: svn+ssh://svn.nta-monitor.com/trunk/opensource/ike-scan@8647 062a1500-4a13-0410-a63b-ee65f32af78f

diff --git a/check-packet b/check-packet
--- a/check-packet
+++ b/check-packet
@@ -14,6 +14,7 @@ TMPFILE=/tmp/ike-scan-test.$$.tmp
 #
 SAMPLE01="$srcdir/pkt-default-proposal.dat"
 SAMPLE02="$srcdir/pkt-custom-proposal.dat"
+SAMPLE03="$srcdir/pkt-aggressive.dat"
 #
 echo "Checking default ike-scan packet against $SAMPLE01 ..."
 IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef"
@@ -41,6 +42,23 @@ if test $? -ne 0; then
    exit 1
 fi
 cmp -s $TMPFILE $SAMPLE02
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+echo "ok"
+rm -f $TMPFILE
+#
+echo "Checking aggressive ike-scan packet against $SAMPLE03 ..."
+IKEARGS="--sport=0 --retry=1 --nodns --cookie=deadbeefdeadbeef --randomseed=1234 --aggressive --id=royhills@hotmail.com"
+$srcdir/ike-scan $IKEARGS --writepkttofile=$TMPFILE 127.0.0.1 >/dev/null 2>&1
+if test $? -ne 0; then
+   rm -f $TMPFILE
+   echo "FAILED"
+   exit 1
+fi
+cmp -s $TMPFILE $SAMPLE03
 if test $? -ne 0; then
    rm -f $TMPFILE
    echo "FAILED"
